//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Морской_бой {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class String {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal String() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Морской_бой.String", typeof(String).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Координаты.
        /// </summary>
        internal static string CoordinatesComboBox {
            get {
                return ResourceManager.GetString("CoordinatesComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите тип корабля.
        /// </summary>
        internal static string HeaderForShiptypeComboBox {
            get {
                return ResourceManager.GetString("HeaderForShiptypeComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Есть попадание!.
        /// </summary>
        internal static string HitMessage {
            get {
                return ResourceManager.GetString("HitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Например: J8.
        /// </summary>
        internal static string InfoForCoordinatesTextBox_1 {
            get {
                return ResourceManager.GetString("InfoForCoordinatesTextBox_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Например: A9,A8.
        /// </summary>
        internal static string InfoForCoordinatesTextBox_2 {
            get {
                return ResourceManager.GetString("InfoForCoordinatesTextBox_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Например: I3,I4,I5.
        /// </summary>
        internal static string InfoForCoordinatesTextBox_3 {
            get {
                return ResourceManager.GetString("InfoForCoordinatesTextBox_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Например: E0,E1,E2,E3.
        /// </summary>
        internal static string InfoForCoordinatesTextBox_4 {
            get {
                return ResourceManager.GetString("InfoForCoordinatesTextBox_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Промах!.
        /// </summary>
        internal static string MissMessage {
            get {
                return ResourceManager.GetString("MissMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершить расcтановку.
        /// </summary>
        internal static string ReadyButton {
            get {
                return ResourceManager.GetString("ReadyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  палубные корабли закончились!.
        /// </summary>
        internal static string ShipOutOfStock {
            get {
                return ResourceManager.GetString("ShipOutOfStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корабль успешно размещен по координатам:.
        /// </summary>
        internal static string ShipSuccessfullyPlacedMessage {
            get {
                return ResourceManager.GetString("ShipSuccessfullyPlacedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  палубный.
        /// </summary>
        internal static string ShipTypeComboBox {
            get {
                return ResourceManager.GetString("ShipTypeComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтвердить ввод.
        /// </summary>
        internal static string SubmitCoordinatesButton {
            get {
                return ResourceManager.GetString("SubmitCoordinatesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расстановка завершена, нажмите кнопку чтобы передать ход следующему игроку.
        /// </summary>
        internal static string TurnEndedMessage {
            get {
                return ResourceManager.GetString("TurnEndedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Морской бой.
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Победил игрок.
        /// </summary>
        internal static string WinMessage {
            get {
                return ResourceManager.GetString("WinMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно разместить корабль, проверьте правильность ввода координат!.
        /// </summary>
        internal static string WrongCoordinatesMessage {
            get {
                return ResourceManager.GetString("WrongCoordinatesMessage", resourceCulture);
            }
        }
    }
}
